In [2]:
import torch

In [7]:
t1= torch.tensor(1)
type(t1),t1.dtype

(torch.Tensor, torch.int64)

In [10]:
t1= torch.tensor(1.)
t1.dtype,t1.shape

(torch.float32, torch.Size([]))

In [22]:
## Creating  tensors
x=torch.tensor(2.0,)
w=torch.tensor(3.0,requires_grad=True)
b=torch.tensor(4.0,requires_grad=True)


# Required_grad is used to calculate the gradients of the tensors 

In [23]:
y=w*x+b

In [24]:
## Now as the requires_grad is true for w and b, we can calculate the gradients of y with respect to w and b
y.backward()   # this is to compute the gradients of y with respect to w and b

In [25]:
## We can access the gradients using the grad attribute of the tensors
x.grad,w.grad,b.grad

(None, tensor(2.), tensor(1.))

In [26]:
import numpy as np

In [27]:
x= np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [29]:
y=torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [30]:
type(y)

torch.Tensor

In [32]:
z=y.numpy()
print(type(z))

<class 'numpy.ndarray'>


In [34]:
torch.full((3,3),2).reshape(9,)

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2])